name: bico_certo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # Comunicação com BACKEND.
  http: ^1.5.0
  # Pegar informações do aparelho.
  device_info_plus: ^12.1.0
  # Armazenar dados simples de forma persistente no dispositivo.
  shared_preferences: ^2.2.3
  # Armazenar dados sensiveis.
  flutter_secure_storage: ^9.2.4
  # Funcionalidade abrir o app via link (usada no email).
  app_links: ^6.4.1
  # Fonts
  google_fonts: ^6.3.2
  # Dashboard - Graficos
  fl_chart: ^1.1.1
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  provider: ^6.1.1
  flutter_dotenv: ^6.0.0
  image_picker: ^1.0.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  open_file: ^3.3.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Bold.ttf
          weight: 700